SPSH-1481 fix tests
dBildungsplattform/schulportal-testautomatisierung pull request #104
Opened 2024-11-22 13:12 UTC by jakobmadp

https://ticketsystem.dbildungscloud.de/browse/SPSH-1481

2024-11-25 08:44 UTC, jaggarnaut requested changes

2024-11-25 08:44 UTC, jaggarnaut commented on tests/workflow.spec.ts
> +let username: string[] = []; // Im afterEach Block werden alle Testdaten gelöscht
```suggestion
let usernames: string[] = []; // Im afterEach Block werden alle Testdaten gelöscht
```
weil es ein array von strings ist

2024-11-26 08:23 UTC, jaggarnaut commented on tests/workflow.spec.ts
> +let username: string[] = []; // Im afterEach Block werden alle Testdaten gelöscht
Die Verwendung der Variable muss auch angepasst werden.

2024-11-26 16:45 UTC, jakobmadp commented on tests/workflow.spec.ts
> +let username: string[] = []; // Im afterEach Block werden alle Testdaten gelöscht
done

2024-11-27 09:23 UTC, jaggarnaut approved these changes

2024-11-27 09:40 UTC, merged