SPSH-975
dBildungsplattform/schulportal-testautomatisierung pull request #108
Opened 2024-12-04 16:47 UTC by DeFi3298

Ticket: https://ticketsystem.dbildungscloud.de/browse/SPSH-975

2024-12-05 11:32 UTC, jaggarnaut requested changes

2024-12-05 11:32 UTC, jaggarnaut commented on tests/Klasse.spec.ts
> +      const klasseManagementView = new KlasseManagementViewPage(page);
Bitte dies hier löschen und im nächsten Step mit `FromAnywhere(page).start()` anfangen und von dort aus die jeweiligen Methoden nutzen, um die gewünschte Seite klasseCreationView zu returnen. Beispiel in Import.spec.ts ab Z31.

2024-12-05 11:32 UTC, jaggarnaut commented on tests/Klasse.spec.ts
> +      const klasseManagementView = new KlasseManagementViewPage(page);
siehe oben

2024-12-06 07:34 UTC, jaggarnaut requested changes

2024-12-06 07:34 UTC, jaggarnaut commented on tests/Klasse.spec.ts
> +    const klasseDetailsView = new KlasseDetailsViewPage(page);
Bitte dies hier löschen und im nächsten Step mit FromAnywhere(page).start() anfangen und von dort aus die jeweiligen Methoden nutzen, um die gewünschte Seite klasseCreationView zu returnen. Beispiel in Import.spec.ts ab Z31.

menue kann bestehen bleiben, damit navigiert werden kann

2024-12-06 07:34 UTC, jaggarnaut commented on tests/Klasse.spec.ts
> +    const klasseDetailsView = new KlasseDetailsViewPage(page);
siehe oben

2024-12-09 10:59 UTC, jakobmadp commented on tests/Klasse.spec.ts
> +      const addminVorname = 'TAuto-PW-V-' + faker.person.firstName();
Bei Vornamen/Nachnamen bitte die entsprechenden Methoden verwenden, wie z.B. generateVorname(), das gleichen für den nachfolgenden Testfall

2024-12-09 11:04 UTC, jakobmadp commented on tests/Klasse.spec.ts
> +      const adminOrganisation = 'Land Schleswig-Holstein';
Den Organisationsnamen bitte aus organisation.ts importieren

2024-12-09 11:07 UTC, jakobmadp requested changes
Siehe Kommentar von heute

2024-12-09 13:41 UTC, DeFi3298 commented on tests/Klasse.spec.ts
> +      const adminOrganisation = 'Land Schleswig-Holstein';
Erledigt.

2024-12-11 07:47 UTC, jakobmadp approved these changes

2024-12-11 12:38 UTC, jaggarnaut approved these changes

2024-12-11 12:39 UTC, merged