SPSH-969: Add test for 2FA Self Service
dBildungsplattform/schulportal-testautomatisierung pull request #119
Opened 2024-12-18 09:51 UTC by clauyan

# Description

## Links to Tickets or other PRs

## Notes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-12-19 14:31 UTC, jakobmadp requested changes

2024-12-19 14:31 UTC, jakobmadp commented on tests/Profile.spec.ts
> +    { tag: [LONG, STAGE] },
I recommend to put the test in the testsuite LONG only,  because we need a proof for the stability before running in testsuite STAGE.

2024-12-19 14:31 UTC, jakobmadp commented on tests/Profile.spec.ts
> +      const rollenart = 'LERN';
Can you please get the value LERN from rollentypen.ts?

2025-01-07 14:31 UTC, clauyan commented on tests/Profile.spec.ts
> +      page.keyboard.press('Escape');
I ran into issues with the clean-up, if dialogues were still open. Usually the tests will close any modal they opened, but if they don't for whatever reason, the modals will block interaction with the page and prevent proper clean-up.

I figured this does no harm: Worst-case, it does nothing, best case: clean-up works, even if some test did not finish properly.

2025-01-07 14:31 UTC, clauyan commented on tests/Profile.spec.ts
> +      const rollenart = 'LERN';
Done!

2025-01-07 14:33 UTC, clauyan commented on tests/Profile.spec.ts
> +    { tag: [LONG, STAGE] },
Done!

2025-01-10 11:40 UTC, merged