Spsh 980 lock user
dBildungsplattform/schulportal-testautomatisierung pull request #83
Opened 2024-11-06 11:17 UTC by jakobmadp

https://ticketsystem.dbildungscloud.de/browse/SPSH-980
- 2 Testfälle, Benutzer sperren unbefristet und Benutzer sperren befristet

2024-11-12 10:01 UTC, kristoff-kiefer requested changes
Needs a little restructuring I feel

2024-11-14 08:43 UTC, jaggarnaut requested changes

2024-11-14 08:43 UTC, jaggarnaut commented on base/rolesTypes.ts
Bitte "rollentypen" verwenden, weil Keyword

2024-11-14 08:43 UTC, jaggarnaut commented on pages/admin/PersonManagementView.page.ts
> +    await page.getByRole("cell", { name: name, exact: true }).click();
```suggestion
    await page.getByRolle("cell", { name: name, exact: true }).click();
```

2024-11-14 10:35 UTC, jakobmadp commented on pages/admin/PersonManagementView.page.ts
> +    await page.getByRole("cell", { name: name, exact: true }).click();
Das geht nicht, getByRole ist eine interne Playwright Funktion

2024-11-15 13:40 UTC, kristoff-kiefer approved these changes

2024-11-15 15:20 UTC, jaggarnaut approved these changes

2024-11-18 10:35 UTC, merged